[[redirects]]
from = "/preview/:slug/"
to = "/.netlify/functions/preview"
status = 200
force = true
_generated_by_eleventy_serverless = "preview"

[[redirects]]
from = "/preview/"
to = "/.netlify/functions/preview"
status = 200
force = true
_generated_by_eleventy_serverless = "preview"
